language: node_js
node_js:
- stable
branchs:
  only:
  - master
install:
- npm install
- npm install --save hexo-deployer-git
- npm install -g hexo-cli
addons:
  ssh_known_hosts:
  - 8.210.131.194
before_install:
- openssl aes-256-cbc -K $encrypted_f217180e22ee_key -iv $encrypted_f217180e22ee_iv
  -in .travis/id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "chenhang"
- git config --global user.email "545192053@qq.com"
script:
- npm run deploy
