language: node_js
node_js:
- stable
branchs:
  only:
  - master
install:
  - npm install
  - npm install --save hexo-deployer-git #hexo提交依赖
addons:
  ssh_known_hosts:
  - 39.106.120.32
before_install:
- openssl aes-256-cbc -K $encrypted_83cbab1bbca1_key -iv $encrypted_83cbab1bbca1_iv
  -in id_rsa.enc -out .travis/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
- git config --global user.name "陈航" #设置github用户名
- git config --global user.email 545192053@qq.com #设置github用户邮箱
  # 执行的命令
after_success:
  - ssh travis@39.106.120.32 -o StrictHostKeyChecking=no 'cd ~/sync-yuqueToBlog  && git pull && npm run deploy'
script:
  - npm run deploy
